version: '3.7'
services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ypsi_cloud_rh_v6
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - '3306'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony_serveur
        restart: always
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            PMA_HOST: database
        networks:
            - dev

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: access1234
            MINIO_ROOT_PASSWORD: secret1234
        volumes:
            - data1-1:/data
        command: server /data --console-address ":9001"
        ports:
            - "9001:9000"
            - "9002:9001"

volumes:
    data1-1:
networks:
    dev: